### ISSUE TITLE
Add support for max page jumps

### ISSUE THREAD

**Issue by DanielCardonaRojas** [kwkarlwang/bufjump.nvim#3]
Hey @kwkarlwang thanks for this awesome plugin I've been using it daily and works great.

Sometimes I've found my self navigating very deeply into the navigation history by accident and opening more buffers then I want to.  

It occurred to me that it would be nice to have some option to support wrapping behaviour after certain configurable maximum number of page jumps. So if you go back more than intended you will get back to the most recent page.

**Comment by kwkarlwang** [comment]
Hi Daniel, I am very glad that you enjoy the plugin.

Let me see if I get your point. If we have 4 files on the jumplist stack: file 1, file 2, file 3, and file 4. And we are currently at file 4 with maximum number of page jumps of 2. Does that mean when we jump backward to file 2, and jump one more time, it should wrap back to file 4?

If that is your request, I am not sure if I can implement it without complicating the codebase. Because for `<C-o>` and `<C-i>` does not support maximum number of jumps, which means we would have to mimic the jumps with a counter, and increment the counter when we execute a page jump. Then the question becomes, when do we reset the counter?  Do we reset the counter when jumplist changes? Unfortunately, there is no `autocmd` or callback function to check if the jumplist has changed.
